# Generated by Django 5.1.1 on 2024-09-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('file_hash', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='A single word associated with the mask', max_length=100)),
                ('mask', models.ImageField(blank=True, help_text='Optional PNG mask file associated with the word', null=True, upload_to='masks/')),
                ('image', models.ForeignKey(default=None, help_text='The image associated with this word-mask entry', on_delete=django.db.models.deletion.CASCADE, related_name='word_masks', to='ImageAnnotatorSAM2.image')),
            ],
        ),
    ]
