# Generated by Django 5.1.1 on 2024-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='mask',
            field=models.ImageField(blank=True, help_text='Optional PNG mask file associated with the word', null=True, upload_to='mediaMasks/'),
        ),
    ]
