# Generated by Django 5.1.1 on 2024-10-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0002_alter_image_file_alter_word_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='mask',
        ),
    ]
