# Generated by Django 5.1.1 on 2024-10-08 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0003_remove_word_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, default=None, help_text='The file path of the uploaded image', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_hash',
            field=models.CharField(default=None, help_text='A unique hash representing the content of the image', max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='The name of the image', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ForeignKey(default=None, help_text='The image associated with this word-mask entry', on_delete=django.db.models.deletion.CASCADE, related_name='assocaited_words', to='ImageAnnotatorSAM2.image'),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskImage', models.ImageField(help_text='The image file representing the mask', upload_to='masks/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ForeignKey(help_text='The image associated with this mask', on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='ImageAnnotatorSAM2.image')),
                ('word', models.ForeignKey(blank=True, help_text='The word associated with this mask (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_masks', to='ImageAnnotatorSAM2.word')),
            ],
        ),
    ]
