# Generated by Django 5.1.1 on 2024-10-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0004_alter_image_file_alter_image_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='mask',
            field=models.ImageField(blank=True, help_text='Optional PNG mask file associated with the word', null=True, upload_to='masks/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_hash',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ForeignKey(default=None, help_text='The image associated with this word-mask entry', on_delete=django.db.models.deletion.CASCADE, related_name='word_masks', to='ImageAnnotatorSAM2.image'),
        ),
        migrations.DeleteModel(
            name='Mask',
        ),
    ]
