# Generated by Django 5.1.1 on 2024-10-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0006_remove_word_mask_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_hash',
            field=models.CharField(blank=True, default=None, help_text='A unique hash representing the content of the image', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ForeignKey(help_text='The image associated with this word-mask entry', on_delete=django.db.models.deletion.CASCADE, related_name='word_masks', to='ImageAnnotatorSAM2.image'),
        ),
    ]
