# Generated by Django 5.1.1 on 2024-10-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnnotatorSAM2', '0008_alter_mask_word'),
        ('ImageAnnotatorSAM2', '0008_mask_contours_alter_mask_word_and_more'),
    ]

    operations = [
    ]
